// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/spam-tracker/Alert.tsx": () => import("../components/mockups/spam-tracker/Alert.tsx"),
  "./components/mockups/spam-tracker/Shield.tsx": () => import("../components/mockups/spam-tracker/Shield.tsx"),
  "./components/mockups/spam-tracker/Trust.tsx": () => import("../components/mockups/spam-tracker/Trust.tsx")
};
