const { withAndroidManifest } = require("expo/config-plugins");

/**
 * Opts Netraksh out of the Android 16 (API 36) large-screen behavior change
 * that ignores orientation/resizability restrictions on large-screen devices
 * (tablets, foldables). Netraksh is a portrait-only, phone-first design, so
 * without this Google Play shows the "Remove resizability and orientation
 * restrictions in your app to support large screen devices" warning, and large
 * screens would force-rotate / stretch the portrait UI.
 *
 * It injects the official opt-out manifest property into <application>:
 *   android.window.PROPERTY_COMPAT_ALLOW_RESTRICTED_RESIZABILITY = true
 * (developer.android.com/guide/practices/device-compatibility-mode#opt_out)
 *
 * The app-level AndroidManifest is generated by prebuild, so the property must
 * be injected via a config plugin rather than edited in a checked-in file.
 *
 * Note: `orientation: "portrait"` in app.json still governs phones (< sw600dp).
 * This opt-out is temporary — Android removes it at API level 37, after which
 * large screens always ignore these restrictions; the long-term fix is adaptive
 * layouts. No permission and no Play Permissions Declaration is involved.
 */
const PROPERTY_NAME =
  "android.window.PROPERTY_COMPAT_ALLOW_RESTRICTED_RESIZABILITY";

const withLargeScreenOptOut = (config) => {
  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0];
    if (!application) return cfg;
    if (!Array.isArray(application.property)) application.property = [];
    const exists = application.property.some(
      (p) => p?.$?.["android:name"] === PROPERTY_NAME,
    );
    if (!exists) {
      application.property.push({
        $: { "android:name": PROPERTY_NAME, "android:value": "true" },
      });
    }
    return cfg;
  });
};

module.exports = withLargeScreenOptOut;
