const { AndroidConfig, withAndroidManifest } = require("expo/config-plugins");

/**
 * Lets Netraksh's incoming-call alert (and the post-call report screen it can
 * open) display OVER the lock screen and wake the device, so the caller card
 * fronts immediately when a call arrives while the phone is locked or the
 * screen is off.
 *
 * Why this is needed: the native CallScreeningService launches the Expo
 * MainActivity (via a full-screen-intent notification and, when the overlay
 * permission is held, a direct background start). Without these activity
 * attributes the launched activity renders BEHIND the keyguard and the screen
 * never turns on, so the user only sees the alert after manually unlocking —
 * the exact "popup doesn't appear on the lock screen" symptom.
 *
 * `android:showWhenLocked` lets the activity show on top of the keyguard;
 * `android:turnScreenOn` wakes a dozing/off display when it is brought forward
 * by the full-screen intent. Both are standard activity manifest attributes —
 * no restricted permission and no Play Permissions Declaration is involved.
 *
 * The app-level AndroidManifest is generated by prebuild, so these attributes
 * must be injected via a config plugin rather than edited in a checked-in file.
 */
const withLockScreenCallAlert = (config) => {
  return withAndroidManifest(config, (cfg) => {
    const mainActivity = AndroidConfig.Manifest.getMainActivityOrThrow(
      cfg.modResults,
    );
    mainActivity.$["android:showWhenLocked"] = "true";
    mainActivity.$["android:turnScreenOn"] = "true";
    return cfg;
  });
};

module.exports = withLockScreenCallAlert;
